// ng-frontend/src/app/features/auth/components/auth-wrapper/auth-wrapper.component.ts
import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  MatCard,
  MatCardActions,
  MatCardContent,
  MatCardHeader,
  MatCardTitle,
  MatCardAvatar,
} from '@angular/material/card';
import { MatButton } from '@angular/material/button';

@Component({
  selector: 'app-auth-wrapper',
  standalone: true,
  imports: [
    RouterLink,
    MatCard,
    MatCardHeader,
    MatCardContent,
    MatCardActions,
    MatCardTitle,
    MatButton,
    MatCardAvatar,
  ],
  templateUrl: './auth-wrapper.component.html',
})
export class AuthWrapperComponent {
  heading = input.required<string>();
  backButtonLabel = input<string>();
  backButtonHref = input<string>();
}

<div class="flex h-full items-center justify-center">
  <mat-card class="w-120">
    <mat-card-header class="flex flex-row items-center justify-center gap-2">
      <img matCardAvatar src="/images/logo.svg" alt="Vendee logo" width="35" height="35" />
      <mat-card-title class="text-2xl">
        {{ heading() }}
      </mat-card-title>
    </mat-card-header>
    <mat-card-content class="mt-2">
      <ng-content />
    </mat-card-content>
    <mat-card-actions class="border-0">
      @if (backButtonLabel() && backButtonHref()) {
        <a mat-button class="text-primary h-10 w-full" [routerLink]="backButtonHref()">
          {{ backButtonLabel() }}
        </a>
      }
    </mat-card-actions>
  </mat-card>
</div>

// frontend/src/features/auth/components/AuthWrapper.tsx
import Image from 'next/image'
import Link from 'next/link'
import { PropsWithChildren } from 'react'

import {
  Button,
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/common'

interface AuthWrapperProps {
  heading: string
  backButtonLabel?: string
  backButtonHref?: string
}

export function AuthWrapper({
  children,
  heading,
  backButtonLabel,
  backButtonHref,
}: PropsWithChildren<AuthWrapperProps>) {
  return (
    <div className='flex h-full items-center justify-center'>
      <Card className='w-120'>
        <CardHeader className='flex items-center justify-center gap-2'>
          <Image
            src='/images/logo.svg'
            alt='Vendee logo'
            width={35}
            height={35}
          />
          <CardTitle className='text-2xl'>{heading}</CardTitle>
        </CardHeader>
        <CardContent className='mt-2'>{children}</CardContent>
        <CardFooter className='-mt-6 border-0 bg-transparent'>
          {backButtonLabel && backButtonHref && (
            <Button variant='ghost' className='text-primary h-10 w-full'>
              <Link href={backButtonHref}>{backButtonLabel}</Link>
            </Button>
          )}
        </CardFooter>
      </Card>
    </div>
  )
}
